version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: huarami/db
    container_name: vprodb
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    ports:
      - "3306:3306"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: huarami/app
    container_name: vproapp
    ports:
      - "8080:8080"

  vproweb:
    build:
      context: ./Docker-files/web
    image: huarami/web
    container_name: vproweb
    ports:
      - "80:80"
