apiVersion: apps/v1
lind: Deployment
metadata:
    name: vproapp
    labels:
        app: vproapp
spec:
    replicas: 2
    selector:
        matchLabels:
            app: vproapp
    template:
        metadata:
            labels:
                app: vptoapp
        spec:
            containers:
            - name: vproapp
              image: {{.Values.appimg}}
              ports:
              - containerPort: 8080

            initContainers:
            - name: db
              image: busybox
              command: ['sh','-c','until nslookup vprodb;do echo waiting for db;sleep 2;done;']
            - name: mem
              image: busybox
              command: ['sh','-c','until nslookup vprocahe01;do echo waiting for mem;sleep 2;done;']