apiVersion: apps/v1
kind: Deployment
metadata:
    name: vpromq01
    labels:
      app: vpromq01
spec:
    replicas: 2
    selector:
      matchLabels:
        app: vpromq01
    template:
      metadata: 
        labels:
          app: vpromq01
      spec:
        containers:
        - name: vpromq
          image: rabbitmq
          ports:
          - containerPort: 15672
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"

          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: secret
                key: rmqpass 
